### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
    summary: Represents a TimespanConfig.
    name: google.privacy.dlp.v2.StorageConfig.TimespanConfig
    fullName: google.privacy.dlp.v2.StorageConfig.TimespanConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.ITimespanConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#enableAutoPopulationOfTimespanConfig:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#endTime:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#startTime:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#timestampField:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:constructor(1)'
    summary: Constructs a new TimespanConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.StorageConfig.ITimespanConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.ITimespanConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.create:member(1)'
    summary: Creates a new TimespanConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.StorageConfig.ITimespanConfig):
        google.privacy.dlp.v2.StorageConfig.TimespanConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
        description: TimespanConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.ITimespanConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decode:member(1)'
    summary: Decodes a TimespanConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.StorageConfig.TimespanConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
        description: TimespanConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decodeDelimited:member(1)'
    summary: 'Decodes a TimespanConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.StorageConfig.TimespanConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
        description: TimespanConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#enableAutoPopulationOfTimespanConfig:member'
    summary: TimespanConfig enableAutoPopulationOfTimespanConfig.
    name: enableAutoPopulationOfTimespanConfig
    fullName: enableAutoPopulationOfTimespanConfig
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public enableAutoPopulationOfTimespanConfig: boolean;'
      return:
        type:
          - boolean
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encode:member(1)'
    summary: Encodes the specified TimespanConfig message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.StorageConfig.ITimespanConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: TimespanConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.ITimespanConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encodeDelimited:member(1)'
    summary: 'Encodes the specified TimespanConfig message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.StorageConfig.ITimespanConfig, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: TimespanConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.ITimespanConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#endTime:member'
    summary: TimespanConfig endTime.
    name: endTime
    fullName: endTime
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public endTime?: (google.protobuf.ITimestamp|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#endTime~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.fromObject:member(1)'
    summary: Creates a TimespanConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.StorageConfig.TimespanConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
        description: TimespanConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#startTime:member'
    summary: TimespanConfig startTime.
    name: startTime
    fullName: startTime
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public startTime?: (google.protobuf.ITimestamp|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#startTime~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#timestampField:member'
    summary: TimespanConfig timestampField.
    name: timestampField
    fullName: timestampField
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public timestampField?: (google.privacy.dlp.v2.IFieldId|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#timestampField~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#toJSON:member(1)'
    summary: Converts this TimespanConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.toObject:member(1)'
    summary: Creates a plain object from a TimespanConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.StorageConfig.TimespanConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: TimespanConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.verify:member(1)'
    summary: Verifies a TimespanConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.ITimespanConfig:interface'
    name: ITimespanConfig
    fullName: google.privacy.dlp.v2.StorageConfig.ITimespanConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig:class'
    name: TimespanConfig
    fullName: google.privacy.dlp.v2.StorageConfig.TimespanConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#endTime~0:complex'
    name: (google.protobuf.ITimestamp|null)
    fullName: (google.protobuf.ITimestamp|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.protobuf.ITimestamp:interface'
        name: google.protobuf.ITimestamp
        fullName: google.protobuf.ITimestamp
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#startTime~0:complex'
    name: (google.protobuf.ITimestamp|null)
    fullName: (google.protobuf.ITimestamp|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.protobuf.ITimestamp:interface'
        name: google.protobuf.ITimestamp
        fullName: google.protobuf.ITimestamp
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig#timestampField~0:complex'
    name: (google.privacy.dlp.v2.IFieldId|null)
    fullName: (google.privacy.dlp.v2.IFieldId|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFieldId:interface'
        name: google.privacy.dlp.v2.IFieldId
        fullName: google.privacy.dlp.v2.IFieldId
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StorageConfig.TimespanConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
