### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable:interface'
    summary: Properties of an AuxiliaryTable.
    name: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable
    fullName: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable
    langs:
      - typeScript
    type: interface
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#quasiIds:member'
      - >-
        @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#relativeFrequency:member
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#table:member'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#quasiIds:member'
    summary: AuxiliaryTable quasiIds
    name: quasiIds
    fullName: quasiIds
    langs:
      - typeScript
    type: property
    syntax:
      content: 'quasiIds?: (google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.IQuasiIdField[]|null);'
      return:
        type:
          - >-
            @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#quasiIds~0:complex
  - uid: >-
      @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#relativeFrequency:member
    summary: AuxiliaryTable relativeFrequency
    name: relativeFrequency
    fullName: relativeFrequency
    langs:
      - typeScript
    type: property
    syntax:
      content: 'relativeFrequency?: (google.privacy.dlp.v2.IFieldId|null);'
      return:
        type:
          - >-
            @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#relativeFrequency~0:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#table:member'
    summary: AuxiliaryTable table
    name: table
    fullName: table
    langs:
      - typeScript
    type: property
    syntax:
      content: 'table?: (google.privacy.dlp.v2.IBigQueryTable|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#table~0:complex'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#quasiIds~0:complex'
    name: '(google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.IQuasiIdField[]|null)'
    fullName: '(google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.IQuasiIdField[]|null)'
    spec.typeScript:
      - name: (
        fullName: (
      - uid: >-
          @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.IQuasiIdField:interface
        name: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.IQuasiIdField
        fullName: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.IQuasiIdField
      - name: '[]|null)'
        fullName: '[]|null)'
  - uid: >-
      @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#relativeFrequency~0:complex
    name: (google.privacy.dlp.v2.IFieldId|null)
    fullName: (google.privacy.dlp.v2.IFieldId|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFieldId:interface'
        name: google.privacy.dlp.v2.IFieldId
        fullName: google.privacy.dlp.v2.IFieldId
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.IAuxiliaryTable#table~0:complex'
    name: (google.privacy.dlp.v2.IBigQueryTable|null)
    fullName: (google.privacy.dlp.v2.IBigQueryTable|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IBigQueryTable:interface'
        name: google.privacy.dlp.v2.IBigQueryTable
        fullName: google.privacy.dlp.v2.IBigQueryTable
      - name: '|null)'
        fullName: '|null)'
