### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
    summary: Represents a StoredInfoTypeConfig.
    name: google.privacy.dlp.v2.StoredInfoTypeConfig
    fullName: google.privacy.dlp.v2.StoredInfoTypeConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IStoredInfoTypeConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#description:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#dictionary:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#displayName:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#largeCustomDictionary:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#regex:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#type:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:constructor(1)'
    summary: Constructs a new StoredInfoTypeConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IStoredInfoTypeConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IStoredInfoTypeConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.create:member(1)'
    summary: Creates a new StoredInfoTypeConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.IStoredInfoTypeConfig):
        google.privacy.dlp.v2.StoredInfoTypeConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
        description: StoredInfoTypeConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IStoredInfoTypeConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decode:member(1)'
    summary: Decodes a StoredInfoTypeConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.StoredInfoTypeConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
        description: StoredInfoTypeConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decodeDelimited:member(1)'
    summary: 'Decodes a StoredInfoTypeConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.StoredInfoTypeConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
        description: StoredInfoTypeConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#description:member'
    summary: StoredInfoTypeConfig description.
    name: description
    fullName: description
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public description: string;'
      return:
        type:
          - string
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#dictionary:member'
    summary: StoredInfoTypeConfig dictionary.
    name: dictionary
    fullName: dictionary
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public dictionary?: (google.privacy.dlp.v2.CustomInfoType.IDictionary|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#dictionary~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#displayName:member'
    summary: StoredInfoTypeConfig displayName.
    name: displayName
    fullName: displayName
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public displayName: string;'
      return:
        type:
          - string
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encode:member(1)'
    summary: >-
      Encodes the specified StoredInfoTypeConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.IStoredInfoTypeConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: StoredInfoTypeConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IStoredInfoTypeConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified StoredInfoTypeConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IStoredInfoTypeConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: StoredInfoTypeConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IStoredInfoTypeConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.fromObject:member(1)'
    summary: >-
      Creates a StoredInfoTypeConfig message from a plain object. Also converts values to their respective internal
      types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.StoredInfoTypeConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
        description: StoredInfoTypeConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#largeCustomDictionary:member'
    summary: StoredInfoTypeConfig largeCustomDictionary.
    name: largeCustomDictionary
    fullName: largeCustomDictionary
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public largeCustomDictionary?: (google.privacy.dlp.v2.ILargeCustomDictionaryConfig|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#largeCustomDictionary~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#regex:member'
    summary: StoredInfoTypeConfig regex.
    name: regex
    fullName: regex
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public regex?: (google.privacy.dlp.v2.CustomInfoType.IRegex|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#regex~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#toJSON:member(1)'
    summary: Converts this StoredInfoTypeConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.toObject:member(1)'
    summary: Creates a plain object from a StoredInfoTypeConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.StoredInfoTypeConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: StoredInfoTypeConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#type:member'
    summary: StoredInfoTypeConfig type.
    name: type
    fullName: type
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public type?: ("largeCustomDictionary"|"dictionary"|"regex");'
      return:
        type:
          - ("largeCustomDictionary"|"dictionary"|"regex")
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.verify:member(1)'
    summary: Verifies a StoredInfoTypeConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IStoredInfoTypeConfig:interface'
    name: IStoredInfoTypeConfig
    fullName: google.privacy.dlp.v2.IStoredInfoTypeConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig:class'
    name: StoredInfoTypeConfig
    fullName: google.privacy.dlp.v2.StoredInfoTypeConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#dictionary~0:complex'
    name: (google.privacy.dlp.v2.CustomInfoType.IDictionary|null)
    fullName: (google.privacy.dlp.v2.CustomInfoType.IDictionary|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CustomInfoType.IDictionary:interface'
        name: google.privacy.dlp.v2.CustomInfoType.IDictionary
        fullName: google.privacy.dlp.v2.CustomInfoType.IDictionary
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#largeCustomDictionary~0:complex'
    name: (google.privacy.dlp.v2.ILargeCustomDictionaryConfig|null)
    fullName: (google.privacy.dlp.v2.ILargeCustomDictionaryConfig|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ILargeCustomDictionaryConfig:interface'
        name: google.privacy.dlp.v2.ILargeCustomDictionaryConfig
        fullName: google.privacy.dlp.v2.ILargeCustomDictionaryConfig
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig#regex~0:complex'
    name: (google.privacy.dlp.v2.CustomInfoType.IRegex|null)
    fullName: (google.privacy.dlp.v2.CustomInfoType.IRegex|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CustomInfoType.IRegex:interface'
        name: google.privacy.dlp.v2.CustomInfoType.IRegex
        fullName: google.privacy.dlp.v2.CustomInfoType.IRegex
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.StoredInfoTypeConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
