### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
    summary: Represents an InspectJobConfig.
    name: google.privacy.dlp.v2.InspectJobConfig
    fullName: google.privacy.dlp.v2.InspectJobConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IInspectJobConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#actions:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#inspectConfig:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#inspectTemplateName:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#storageConfig:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:constructor(1)'
    summary: Constructs a new InspectJobConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IInspectJobConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IInspectJobConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#actions:member'
    summary: InspectJobConfig actions.
    name: actions
    fullName: actions
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public actions: google.privacy.dlp.v2.IAction[];'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#actions~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.create:member(1)'
    summary: Creates a new InspectJobConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.IInspectJobConfig):
        google.privacy.dlp.v2.InspectJobConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
        description: InspectJobConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IInspectJobConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decode:member(1)'
    summary: Decodes an InspectJobConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.InspectJobConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
        description: InspectJobConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decodeDelimited:member(1)'
    summary: 'Decodes an InspectJobConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.InspectJobConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
        description: InspectJobConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encode:member(1)'
    summary: >-
      Encodes the specified InspectJobConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.IInspectJobConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: InspectJobConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IInspectJobConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified InspectJobConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IInspectJobConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: InspectJobConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IInspectJobConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.fromObject:member(1)'
    summary: Creates an InspectJobConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.InspectJobConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
        description: InspectJobConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#inspectConfig:member'
    summary: InspectJobConfig inspectConfig.
    name: inspectConfig
    fullName: inspectConfig
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public inspectConfig?: (google.privacy.dlp.v2.IInspectConfig|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#inspectConfig~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#inspectTemplateName:member'
    summary: InspectJobConfig inspectTemplateName.
    name: inspectTemplateName
    fullName: inspectTemplateName
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public inspectTemplateName: string;'
      return:
        type:
          - string
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#storageConfig:member'
    summary: InspectJobConfig storageConfig.
    name: storageConfig
    fullName: storageConfig
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public storageConfig?: (google.privacy.dlp.v2.IStorageConfig|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#storageConfig~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#toJSON:member(1)'
    summary: Converts this InspectJobConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.toObject:member(1)'
    summary: Creates a plain object from an InspectJobConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.InspectJobConfig, options?: $protobuf.IConversionOptions):
        { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: InspectJobConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.verify:member(1)'
    summary: Verifies an InspectJobConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IInspectJobConfig:interface'
    name: IInspectJobConfig
    fullName: google.privacy.dlp.v2.IInspectJobConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#actions~0:complex'
    name: 'google.privacy.dlp.v2.IAction[]'
    fullName: 'google.privacy.dlp.v2.IAction[]'
    spec.typeScript:
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IAction:interface'
        name: google.privacy.dlp.v2.IAction
        fullName: google.privacy.dlp.v2.IAction
      - name: '[]'
        fullName: '[]'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig:class'
    name: InspectJobConfig
    fullName: google.privacy.dlp.v2.InspectJobConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#inspectConfig~0:complex'
    name: (google.privacy.dlp.v2.IInspectConfig|null)
    fullName: (google.privacy.dlp.v2.IInspectConfig|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IInspectConfig:interface'
        name: google.privacy.dlp.v2.IInspectConfig
        fullName: google.privacy.dlp.v2.IInspectConfig
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig#storageConfig~0:complex'
    name: (google.privacy.dlp.v2.IStorageConfig|null)
    fullName: (google.privacy.dlp.v2.IStorageConfig|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IStorageConfig:interface'
        name: google.privacy.dlp.v2.IStorageConfig
        fullName: google.privacy.dlp.v2.IStorageConfig
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectJobConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
