### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
    summary: Represents a CryptoHashConfig.
    name: google.privacy.dlp.v2.CryptoHashConfig
    fullName: google.privacy.dlp.v2.CryptoHashConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoHashConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig#cryptoKey:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:constructor(1)'
    summary: Constructs a new CryptoHashConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.ICryptoHashConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoHashConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.create:member(1)'
    summary: Creates a new CryptoHashConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.ICryptoHashConfig):
        google.privacy.dlp.v2.CryptoHashConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
        description: CryptoHashConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoHashConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig#cryptoKey:member'
    summary: CryptoHashConfig cryptoKey.
    name: cryptoKey
    fullName: cryptoKey
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public cryptoKey?: (google.privacy.dlp.v2.ICryptoKey|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig#cryptoKey~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decode:member(1)'
    summary: Decodes a CryptoHashConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.CryptoHashConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
        description: CryptoHashConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decodeDelimited:member(1)'
    summary: 'Decodes a CryptoHashConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.CryptoHashConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
        description: CryptoHashConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encode:member(1)'
    summary: >-
      Encodes the specified CryptoHashConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.ICryptoHashConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: CryptoHashConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoHashConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified CryptoHashConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.ICryptoHashConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: CryptoHashConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoHashConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.fromObject:member(1)'
    summary: Creates a CryptoHashConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.CryptoHashConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
        description: CryptoHashConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig#toJSON:member(1)'
    summary: Converts this CryptoHashConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.toObject:member(1)'
    summary: Creates a plain object from a CryptoHashConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.CryptoHashConfig, options?: $protobuf.IConversionOptions):
        { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: CryptoHashConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.verify:member(1)'
    summary: Verifies a CryptoHashConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoHashConfig:interface'
    name: ICryptoHashConfig
    fullName: google.privacy.dlp.v2.ICryptoHashConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig:class'
    name: CryptoHashConfig
    fullName: google.privacy.dlp.v2.CryptoHashConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig#cryptoKey~0:complex'
    name: (google.privacy.dlp.v2.ICryptoKey|null)
    fullName: (google.privacy.dlp.v2.ICryptoKey|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ICryptoKey:interface'
        name: google.privacy.dlp.v2.ICryptoKey
        fullName: google.privacy.dlp.v2.ICryptoKey
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CryptoHashConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
