### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
    summary: Represents a LDiversityConfig.
    name: google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#quasiIds:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#sensitiveAttribute:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:constructor(1)'
    summary: Constructs a new LDiversityConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.create:member(1)'
    summary: Creates a new LDiversityConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig):
        google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
        description: LDiversityConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decode:member(1)'
    summary: Decodes a LDiversityConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
        description: LDiversityConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decodeDelimited:member(1)'
    summary: 'Decodes a LDiversityConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
        description: LDiversityConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encode:member(1)'
    summary: Encodes the specified LDiversityConfig message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: LDiversityConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encodeDelimited:member(1)'
    summary: 'Encodes the specified LDiversityConfig message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: LDiversityConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.fromObject:member(1)'
    summary: Creates a LDiversityConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
        description: LDiversityConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#quasiIds:member'
    summary: LDiversityConfig quasiIds.
    name: quasiIds
    fullName: quasiIds
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public quasiIds: google.privacy.dlp.v2.IFieldId[];'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#quasiIds~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#sensitiveAttribute:member'
    summary: LDiversityConfig sensitiveAttribute.
    name: sensitiveAttribute
    fullName: sensitiveAttribute
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public sensitiveAttribute?: (google.privacy.dlp.v2.IFieldId|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#sensitiveAttribute~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#toJSON:member(1)'
    summary: Converts this LDiversityConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.toObject:member(1)'
    summary: Creates a plain object from a LDiversityConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: LDiversityConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.verify:member(1)'
    summary: Verifies a LDiversityConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig:interface'
    name: ILDiversityConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.ILDiversityConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig:class'
    name: LDiversityConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#quasiIds~0:complex'
    name: 'google.privacy.dlp.v2.IFieldId[]'
    fullName: 'google.privacy.dlp.v2.IFieldId[]'
    spec.typeScript:
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFieldId:interface'
        name: google.privacy.dlp.v2.IFieldId
        fullName: google.privacy.dlp.v2.IFieldId
      - name: '[]'
        fullName: '[]'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig#sensitiveAttribute~0:complex'
    name: (google.privacy.dlp.v2.IFieldId|null)
    fullName: (google.privacy.dlp.v2.IFieldId|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFieldId:interface'
        name: google.privacy.dlp.v2.IFieldId
        fullName: google.privacy.dlp.v2.IFieldId
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
