### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
    summary: Represents a DeidentifyConfig.
    name: google.privacy.dlp.v2.DeidentifyConfig
    fullName: google.privacy.dlp.v2.DeidentifyConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IDeidentifyConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#infoTypeTransformations:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#recordTransformations:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#transformation:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#transformationErrorHandling:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:constructor(1)'
    summary: Constructs a new DeidentifyConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IDeidentifyConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IDeidentifyConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.create:member(1)'
    summary: Creates a new DeidentifyConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.IDeidentifyConfig):
        google.privacy.dlp.v2.DeidentifyConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
        description: DeidentifyConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IDeidentifyConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decode:member(1)'
    summary: Decodes a DeidentifyConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.DeidentifyConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
        description: DeidentifyConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decodeDelimited:member(1)'
    summary: 'Decodes a DeidentifyConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.DeidentifyConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
        description: DeidentifyConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encode:member(1)'
    summary: >-
      Encodes the specified DeidentifyConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.IDeidentifyConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: DeidentifyConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IDeidentifyConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified DeidentifyConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IDeidentifyConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: DeidentifyConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IDeidentifyConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.fromObject:member(1)'
    summary: Creates a DeidentifyConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.DeidentifyConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
        description: DeidentifyConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#infoTypeTransformations:member'
    summary: DeidentifyConfig infoTypeTransformations.
    name: infoTypeTransformations
    fullName: infoTypeTransformations
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public infoTypeTransformations?: (google.privacy.dlp.v2.IInfoTypeTransformations|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#infoTypeTransformations~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#recordTransformations:member'
    summary: DeidentifyConfig recordTransformations.
    name: recordTransformations
    fullName: recordTransformations
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public recordTransformations?: (google.privacy.dlp.v2.IRecordTransformations|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#recordTransformations~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#toJSON:member(1)'
    summary: Converts this DeidentifyConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.toObject:member(1)'
    summary: Creates a plain object from a DeidentifyConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.DeidentifyConfig, options?: $protobuf.IConversionOptions):
        { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: DeidentifyConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#transformation:member'
    summary: DeidentifyConfig transformation.
    name: transformation
    fullName: transformation
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public transformation?: ("infoTypeTransformations"|"recordTransformations");'
      return:
        type:
          - ("infoTypeTransformations"|"recordTransformations")
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#transformationErrorHandling:member'
    summary: DeidentifyConfig transformationErrorHandling.
    name: transformationErrorHandling
    fullName: transformationErrorHandling
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public transformationErrorHandling?: (google.privacy.dlp.v2.ITransformationErrorHandling|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#transformationErrorHandling~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.verify:member(1)'
    summary: Verifies a DeidentifyConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IDeidentifyConfig:interface'
    name: IDeidentifyConfig
    fullName: google.privacy.dlp.v2.IDeidentifyConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig:class'
    name: DeidentifyConfig
    fullName: google.privacy.dlp.v2.DeidentifyConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#infoTypeTransformations~0:complex'
    name: (google.privacy.dlp.v2.IInfoTypeTransformations|null)
    fullName: (google.privacy.dlp.v2.IInfoTypeTransformations|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IInfoTypeTransformations:interface'
        name: google.privacy.dlp.v2.IInfoTypeTransformations
        fullName: google.privacy.dlp.v2.IInfoTypeTransformations
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#recordTransformations~0:complex'
    name: (google.privacy.dlp.v2.IRecordTransformations|null)
    fullName: (google.privacy.dlp.v2.IRecordTransformations|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IRecordTransformations:interface'
        name: google.privacy.dlp.v2.IRecordTransformations
        fullName: google.privacy.dlp.v2.IRecordTransformations
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.DeidentifyConfig#transformationErrorHandling~0:complex'
    name: (google.privacy.dlp.v2.ITransformationErrorHandling|null)
    fullName: (google.privacy.dlp.v2.ITransformationErrorHandling|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ITransformationErrorHandling:interface'
        name: google.privacy.dlp.v2.ITransformationErrorHandling
        fullName: google.privacy.dlp.v2.ITransformationErrorHandling
      - name: '|null)'
        fullName: '|null)'
