### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig:interface'
    summary: Properties of a NumericalStatsConfig.
    name: google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig
    langs:
      - typeScript
    type: interface
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig#field:member'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig#field:member'
    summary: NumericalStatsConfig field
    name: field
    fullName: field
    langs:
      - typeScript
    type: property
    syntax:
      content: 'field?: (google.privacy.dlp.v2.IFieldId|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig#field~0:complex'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.INumericalStatsConfig#field~0:complex'
    name: (google.privacy.dlp.v2.IFieldId|null)
    fullName: (google.privacy.dlp.v2.IFieldId|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFieldId:interface'
        name: google.privacy.dlp.v2.IFieldId
        fullName: google.privacy.dlp.v2.IFieldId
      - name: '|null)'
        fullName: '|null)'
