### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
    summary: Represents an InfoTypeLimit.
    name: google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit
    fullName: google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#infoType:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#maxFindings:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:constructor(1)'
    summary: Constructs a new InfoTypeLimit.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.create:member(1)'
    summary: Creates a new InfoTypeLimit instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit):
        google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
        description: InfoTypeLimit instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decode:member(1)'
    summary: Decodes an InfoTypeLimit message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
        description: InfoTypeLimit
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decodeDelimited:member(1)'
    summary: 'Decodes an InfoTypeLimit message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
        description: InfoTypeLimit
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - >-
              @google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decodeDelimited~0:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encode:member(1)'
    summary: Encodes the specified InfoTypeLimit message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: InfoTypeLimit message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encodeDelimited:member(1)'
    summary: 'Encodes the specified InfoTypeLimit message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit,
        writer?: $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: InfoTypeLimit message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
        - id: writer
          description: Writer to encode to
          type:
            - >-
              @google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encodeDelimited~1:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.fromObject:member(1)'
    summary: Creates an InfoTypeLimit message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static fromObject(object: { [k: string]: any }):
        google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
        description: InfoTypeLimit
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#infoType:member'
    summary: InfoTypeLimit infoType.
    name: infoType
    fullName: infoType
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public infoType?: (google.privacy.dlp.v2.IInfoType|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#infoType~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#maxFindings:member'
    summary: InfoTypeLimit maxFindings.
    name: maxFindings
    fullName: maxFindings
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public maxFindings: number;'
      return:
        type:
          - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#toJSON:member(1)'
    summary: Converts this InfoTypeLimit to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.toObject:member(1)'
    summary: Creates a plain object from an InfoTypeLimit message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: InfoTypeLimit
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.verify:member(1)'
    summary: Verifies an InfoTypeLimit message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
    name: IInfoTypeLimit
    fullName: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit:class'
    name: InfoTypeLimit
    fullName: google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit#infoType~0:complex'
    name: (google.privacy.dlp.v2.IInfoType|null)
    fullName: (google.privacy.dlp.v2.IInfoType|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IInfoType:interface'
        name: google.privacy.dlp.v2.IInfoType
        fullName: google.privacy.dlp.v2.IInfoType
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.InfoTypeLimit.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
