### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
    summary: Properties of a RedactConfig.
    name: google.privacy.dlp.v2.IRedactConfig
    fullName: google.privacy.dlp.v2.IRedactConfig
    langs:
      - typeScript
    type: interface
    package: '@google-cloud/dlp!'
