### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
    summary: Represents a FixedSizeBucketingConfig.
    name: google.privacy.dlp.v2.FixedSizeBucketingConfig
    fullName: google.privacy.dlp.v2.FixedSizeBucketingConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IFixedSizeBucketingConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#bucketSize:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#lowerBound:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#upperBound:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:constructor(1)'
    summary: Constructs a new FixedSizeBucketingConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IFixedSizeBucketingConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IFixedSizeBucketingConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#bucketSize:member'
    summary: FixedSizeBucketingConfig bucketSize.
    name: bucketSize
    fullName: bucketSize
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public bucketSize: number;'
      return:
        type:
          - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.create:member(1)'
    summary: Creates a new FixedSizeBucketingConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.IFixedSizeBucketingConfig):
        google.privacy.dlp.v2.FixedSizeBucketingConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
        description: FixedSizeBucketingConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IFixedSizeBucketingConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decode:member(1)'
    summary: Decodes a FixedSizeBucketingConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.FixedSizeBucketingConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
        description: FixedSizeBucketingConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decodeDelimited:member(1)'
    summary: 'Decodes a FixedSizeBucketingConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.FixedSizeBucketingConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
        description: FixedSizeBucketingConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encode:member(1)'
    summary: >-
      Encodes the specified FixedSizeBucketingConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.IFixedSizeBucketingConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: FixedSizeBucketingConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IFixedSizeBucketingConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified FixedSizeBucketingConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IFixedSizeBucketingConfig, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: FixedSizeBucketingConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IFixedSizeBucketingConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.fromObject:member(1)'
    summary: >-
      Creates a FixedSizeBucketingConfig message from a plain object. Also converts values to their respective internal
      types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.FixedSizeBucketingConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
        description: FixedSizeBucketingConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#lowerBound:member'
    summary: FixedSizeBucketingConfig lowerBound.
    name: lowerBound
    fullName: lowerBound
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public lowerBound?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#lowerBound~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#toJSON:member(1)'
    summary: Converts this FixedSizeBucketingConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.toObject:member(1)'
    summary: Creates a plain object from a FixedSizeBucketingConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.FixedSizeBucketingConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: FixedSizeBucketingConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#upperBound:member'
    summary: FixedSizeBucketingConfig upperBound.
    name: upperBound
    fullName: upperBound
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public upperBound?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#upperBound~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.verify:member(1)'
    summary: Verifies a FixedSizeBucketingConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFixedSizeBucketingConfig:interface'
    name: IFixedSizeBucketingConfig
    fullName: google.privacy.dlp.v2.IFixedSizeBucketingConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig:class'
    name: FixedSizeBucketingConfig
    fullName: google.privacy.dlp.v2.FixedSizeBucketingConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#lowerBound~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.FixedSizeBucketingConfig#upperBound~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
