### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
    summary: Represents a TaggedField.
    name: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField
    fullName: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#customTag:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#field:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#inferred:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#infoType:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#tag:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:constructor(1)'
    summary: Constructs a new TaggedField.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.create:member(1)'
    summary: Creates a new TaggedField instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField):
        google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
        description: TaggedField instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#customTag:member'
    summary: TaggedField customTag.
    name: customTag
    fullName: customTag
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public customTag: string;'
      return:
        type:
          - string
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decode:member(1)'
    summary: Decodes a TaggedField message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
        description: TaggedField
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decodeDelimited:member(1)'
    summary: 'Decodes a TaggedField message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
        description: TaggedField
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - >-
              @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decodeDelimited~0:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encode:member(1)'
    summary: Encodes the specified TaggedField message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: TaggedField message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encodeDelimited:member(1)'
    summary: 'Encodes the specified TaggedField message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField,
        writer?: $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - >-
            @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encodeDelimited~0:complex
        description: Writer
      parameters:
        - id: message
          description: TaggedField message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField:interface'
        - id: writer
          description: Writer to encode to
          type:
            - >-
              @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encodeDelimited~1:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#field:member'
    summary: TaggedField field.
    name: field
    fullName: field
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public field?: (google.privacy.dlp.v2.IFieldId|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#field~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.fromObject:member(1)'
    summary: Creates a TaggedField message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static fromObject(object: { [k: string]: any }):
        google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
        description: TaggedField
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#inferred:member'
    summary: TaggedField inferred.
    name: inferred
    fullName: inferred
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public inferred?: (google.protobuf.IEmpty|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#inferred~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#infoType:member'
    summary: TaggedField infoType.
    name: infoType
    fullName: infoType
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public infoType?: (google.privacy.dlp.v2.IInfoType|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#infoType~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#tag:member'
    summary: TaggedField tag.
    name: tag
    fullName: tag
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public tag?: ("infoType"|"customTag"|"inferred");'
      return:
        type:
          - ("infoType"|"customTag"|"inferred")
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#toJSON:member(1)'
    summary: Converts this TaggedField to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.toObject:member(1)'
    summary: Creates a plain object from a TaggedField message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: TaggedField
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.verify:member(1)'
    summary: Verifies a TaggedField message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField:interface'
    name: ITaggedField
    fullName: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.ITaggedField
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField:class'
    name: TaggedField
    fullName: google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#field~0:complex'
    name: (google.privacy.dlp.v2.IFieldId|null)
    fullName: (google.privacy.dlp.v2.IFieldId|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IFieldId:interface'
        name: google.privacy.dlp.v2.IFieldId
        fullName: google.privacy.dlp.v2.IFieldId
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#inferred~0:complex'
    name: (google.protobuf.IEmpty|null)
    fullName: (google.protobuf.IEmpty|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.protobuf.IEmpty:interface'
        name: google.protobuf.IEmpty
        fullName: google.protobuf.IEmpty
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField#infoType~0:complex'
    name: (google.privacy.dlp.v2.IInfoType|null)
    fullName: (google.privacy.dlp.v2.IInfoType|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IInfoType:interface'
        name: google.privacy.dlp.v2.IInfoType
        fullName: google.privacy.dlp.v2.IInfoType
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
