### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
    summary: Represents a CharacterMaskConfig.
    name: google.privacy.dlp.v2.CharacterMaskConfig
    fullName: google.privacy.dlp.v2.CharacterMaskConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.ICharacterMaskConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#charactersToIgnore:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#maskingCharacter:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#numberToMask:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#reverseOrder:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:constructor(1)'
    summary: Constructs a new CharacterMaskConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.ICharacterMaskConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICharacterMaskConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#charactersToIgnore:member'
    summary: CharacterMaskConfig charactersToIgnore.
    name: charactersToIgnore
    fullName: charactersToIgnore
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public charactersToIgnore: google.privacy.dlp.v2.ICharsToIgnore[];'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#charactersToIgnore~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.create:member(1)'
    summary: Creates a new CharacterMaskConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.ICharacterMaskConfig):
        google.privacy.dlp.v2.CharacterMaskConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
        description: CharacterMaskConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICharacterMaskConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decode:member(1)'
    summary: Decodes a CharacterMaskConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.CharacterMaskConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
        description: CharacterMaskConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decodeDelimited:member(1)'
    summary: 'Decodes a CharacterMaskConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.CharacterMaskConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
        description: CharacterMaskConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encode:member(1)'
    summary: >-
      Encodes the specified CharacterMaskConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.ICharacterMaskConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: CharacterMaskConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICharacterMaskConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified CharacterMaskConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.ICharacterMaskConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: CharacterMaskConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ICharacterMaskConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.fromObject:member(1)'
    summary: >-
      Creates a CharacterMaskConfig message from a plain object. Also converts values to their respective internal
      types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.CharacterMaskConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
        description: CharacterMaskConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#maskingCharacter:member'
    summary: CharacterMaskConfig maskingCharacter.
    name: maskingCharacter
    fullName: maskingCharacter
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public maskingCharacter: string;'
      return:
        type:
          - string
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#numberToMask:member'
    summary: CharacterMaskConfig numberToMask.
    name: numberToMask
    fullName: numberToMask
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public numberToMask: number;'
      return:
        type:
          - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#reverseOrder:member'
    summary: CharacterMaskConfig reverseOrder.
    name: reverseOrder
    fullName: reverseOrder
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public reverseOrder: boolean;'
      return:
        type:
          - boolean
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#toJSON:member(1)'
    summary: Converts this CharacterMaskConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.toObject:member(1)'
    summary: Creates a plain object from a CharacterMaskConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.CharacterMaskConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: CharacterMaskConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.verify:member(1)'
    summary: Verifies a CharacterMaskConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ICharacterMaskConfig:interface'
    name: ICharacterMaskConfig
    fullName: google.privacy.dlp.v2.ICharacterMaskConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig#charactersToIgnore~0:complex'
    name: 'google.privacy.dlp.v2.ICharsToIgnore[]'
    fullName: 'google.privacy.dlp.v2.ICharsToIgnore[]'
    spec.typeScript:
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ICharsToIgnore:interface'
        name: google.privacy.dlp.v2.ICharsToIgnore
        fullName: google.privacy.dlp.v2.ICharsToIgnore
      - name: '[]'
        fullName: '[]'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig:class'
    name: CharacterMaskConfig
    fullName: google.privacy.dlp.v2.CharacterMaskConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.CharacterMaskConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
