### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
    summary: Represents a FindingLimits.
    name: google.privacy.dlp.v2.InspectConfig.FindingLimits
    fullName: google.privacy.dlp.v2.InspectConfig.FindingLimits
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.IFindingLimits:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerInfoType:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerItem:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerRequest:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:constructor(1)'
    summary: Constructs a new FindingLimits.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.InspectConfig.IFindingLimits);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.IFindingLimits:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.create:member(1)'
    summary: Creates a new FindingLimits instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.InspectConfig.IFindingLimits):
        google.privacy.dlp.v2.InspectConfig.FindingLimits;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
        description: FindingLimits instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.IFindingLimits:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decode:member(1)'
    summary: Decodes a FindingLimits message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.InspectConfig.FindingLimits;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
        description: FindingLimits
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decodeDelimited:member(1)'
    summary: 'Decodes a FindingLimits message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.InspectConfig.FindingLimits;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
        description: FindingLimits
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encode:member(1)'
    summary: Encodes the specified FindingLimits message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.InspectConfig.IFindingLimits, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: FindingLimits message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.IFindingLimits:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encodeDelimited:member(1)'
    summary: 'Encodes the specified FindingLimits message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.InspectConfig.IFindingLimits, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: FindingLimits message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.IFindingLimits:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.fromObject:member(1)'
    summary: Creates a FindingLimits message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.InspectConfig.FindingLimits;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
        description: FindingLimits
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerInfoType:member'
    summary: FindingLimits maxFindingsPerInfoType.
    name: maxFindingsPerInfoType
    fullName: maxFindingsPerInfoType
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public maxFindingsPerInfoType: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit[];'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerInfoType~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerItem:member'
    summary: FindingLimits maxFindingsPerItem.
    name: maxFindingsPerItem
    fullName: maxFindingsPerItem
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public maxFindingsPerItem: number;'
      return:
        type:
          - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerRequest:member'
    summary: FindingLimits maxFindingsPerRequest.
    name: maxFindingsPerRequest
    fullName: maxFindingsPerRequest
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public maxFindingsPerRequest: number;'
      return:
        type:
          - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#toJSON:member(1)'
    summary: Converts this FindingLimits to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.toObject:member(1)'
    summary: Creates a plain object from a FindingLimits message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.InspectConfig.FindingLimits, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: FindingLimits
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.verify:member(1)'
    summary: Verifies a FindingLimits message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.IFindingLimits:interface'
    name: IFindingLimits
    fullName: google.privacy.dlp.v2.InspectConfig.IFindingLimits
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits:class'
    name: FindingLimits
    fullName: google.privacy.dlp.v2.InspectConfig.FindingLimits
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits#maxFindingsPerInfoType~0:complex'
    name: 'google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit[]'
    fullName: 'google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit[]'
    spec.typeScript:
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit:interface'
        name: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit
        fullName: google.privacy.dlp.v2.InspectConfig.FindingLimits.IInfoTypeLimit
      - name: '[]'
        fullName: '[]'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.InspectConfig.FindingLimits.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
