### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
    summary: Represents a DeltaPresenceEstimationConfig.
    name: google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#auxiliaryTables:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#quasiIds:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#regionCode:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:constructor(1)'
    summary: Constructs a new DeltaPresenceEstimationConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#auxiliaryTables:member'
    summary: DeltaPresenceEstimationConfig auxiliaryTables.
    name: auxiliaryTables
    fullName: auxiliaryTables
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public auxiliaryTables: google.privacy.dlp.v2.IStatisticalTable[];'
      return:
        type:
          - >-
            @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#auxiliaryTables~0:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.create:member(1)'
    summary: Creates a new DeltaPresenceEstimationConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig):
        google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
        description: DeltaPresenceEstimationConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decode:member(1)'
    summary: Decodes a DeltaPresenceEstimationConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
        description: DeltaPresenceEstimationConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decodeDelimited:member(1)'
    summary: 'Decodes a DeltaPresenceEstimationConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)):
        google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
        description: DeltaPresenceEstimationConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - >-
              @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decodeDelimited~0:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encode:member(1)'
    summary: Encodes the specified DeltaPresenceEstimationConfig message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig, writer?:
        $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: DeltaPresenceEstimationConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encodeDelimited:member(1)'
    summary: 'Encodes the specified DeltaPresenceEstimationConfig message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig,
        writer?: $protobuf.Writer): $protobuf.Writer;
      return:
        type:
          - >-
            @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encodeDelimited~0:complex
        description: Writer
      parameters:
        - id: message
          description: DeltaPresenceEstimationConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - >-
              @google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encodeDelimited~1:complex
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.fromObject:member(1)'
    summary: >-
      Creates a DeltaPresenceEstimationConfig message from a plain object. Also converts values to their respective
      internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static fromObject(object: { [k: string]: any }):
        google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
        description: DeltaPresenceEstimationConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#quasiIds:member'
    summary: DeltaPresenceEstimationConfig quasiIds.
    name: quasiIds
    fullName: quasiIds
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public quasiIds: google.privacy.dlp.v2.IQuasiId[];'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#quasiIds~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#regionCode:member'
    summary: DeltaPresenceEstimationConfig regionCode.
    name: regionCode
    fullName: regionCode
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public regionCode: string;'
      return:
        type:
          - string
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#toJSON:member(1)'
    summary: Converts this DeltaPresenceEstimationConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.toObject:member(1)'
    summary: >-
      Creates a plain object from a DeltaPresenceEstimationConfig message. Also converts values to other types if
      specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: DeltaPresenceEstimationConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.verify:member(1)'
    summary: Verifies a DeltaPresenceEstimationConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig:interface'
    name: IDeltaPresenceEstimationConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.IDeltaPresenceEstimationConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#auxiliaryTables~0:complex'
    name: 'google.privacy.dlp.v2.IStatisticalTable[]'
    fullName: 'google.privacy.dlp.v2.IStatisticalTable[]'
    spec.typeScript:
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IStatisticalTable:interface'
        name: google.privacy.dlp.v2.IStatisticalTable
        fullName: google.privacy.dlp.v2.IStatisticalTable
      - name: '[]'
        fullName: '[]'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig:class'
    name: DeltaPresenceEstimationConfig
    fullName: google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig#quasiIds~0:complex'
    name: 'google.privacy.dlp.v2.IQuasiId[]'
    fullName: 'google.privacy.dlp.v2.IQuasiId[]'
    spec.typeScript:
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IQuasiId:interface'
        name: google.privacy.dlp.v2.IQuasiId
        fullName: google.privacy.dlp.v2.IQuasiId
      - name: '[]'
        fullName: '[]'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
