### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket:interface'
    summary: Properties of a Bucket.
    name: google.privacy.dlp.v2.BucketingConfig.IBucket
    fullName: google.privacy.dlp.v2.BucketingConfig.IBucket
    langs:
      - typeScript
    type: interface
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#max:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#min:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#replacementValue:member'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#max:member'
    summary: Bucket max
    name: max
    fullName: max
    langs:
      - typeScript
    type: property
    syntax:
      content: 'max?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#max~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#min:member'
    summary: Bucket min
    name: min
    fullName: min
    langs:
      - typeScript
    type: property
    syntax:
      content: 'min?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#min~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#replacementValue:member'
    summary: Bucket replacementValue
    name: replacementValue
    fullName: replacementValue
    langs:
      - typeScript
    type: property
    syntax:
      content: 'replacementValue?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#replacementValue~0:complex'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#max~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#min~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.BucketingConfig.IBucket#replacementValue~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
