### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
    summary: Represents a ReplaceValueConfig.
    name: google.privacy.dlp.v2.ReplaceValueConfig
    fullName: google.privacy.dlp.v2.ReplaceValueConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig#newValue:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:constructor(1)'
    summary: Constructs a new ReplaceValueConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IReplaceValueConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.create:member(1)'
    summary: Creates a new ReplaceValueConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.IReplaceValueConfig):
        google.privacy.dlp.v2.ReplaceValueConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
        description: ReplaceValueConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decode:member(1)'
    summary: Decodes a ReplaceValueConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.ReplaceValueConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
        description: ReplaceValueConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decodeDelimited:member(1)'
    summary: 'Decodes a ReplaceValueConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.ReplaceValueConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
        description: ReplaceValueConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encode:member(1)'
    summary: >-
      Encodes the specified ReplaceValueConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.IReplaceValueConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: ReplaceValueConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified ReplaceValueConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IReplaceValueConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: ReplaceValueConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.fromObject:member(1)'
    summary: Creates a ReplaceValueConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.ReplaceValueConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
        description: ReplaceValueConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig#newValue:member'
    summary: ReplaceValueConfig newValue.
    name: newValue
    fullName: newValue
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public newValue?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig#newValue~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig#toJSON:member(1)'
    summary: Converts this ReplaceValueConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.toObject:member(1)'
    summary: Creates a plain object from a ReplaceValueConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.ReplaceValueConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: ReplaceValueConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.verify:member(1)'
    summary: Verifies a ReplaceValueConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
    name: IReplaceValueConfig
    fullName: google.privacy.dlp.v2.IReplaceValueConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig:class'
    name: ReplaceValueConfig
    fullName: google.privacy.dlp.v2.ReplaceValueConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig#newValue~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.ReplaceValueConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
