### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig:interface'
    summary: Properties of a ReplaceValueConfig.
    name: google.privacy.dlp.v2.IReplaceValueConfig
    fullName: google.privacy.dlp.v2.IReplaceValueConfig
    langs:
      - typeScript
    type: interface
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig#newValue:member'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig#newValue:member'
    summary: ReplaceValueConfig newValue
    name: newValue
    fullName: newValue
    langs:
      - typeScript
    type: property
    syntax:
      content: 'newValue?: (google.privacy.dlp.v2.IValue|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig#newValue~0:complex'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IReplaceValueConfig#newValue~0:complex'
    name: (google.privacy.dlp.v2.IValue|null)
    fullName: (google.privacy.dlp.v2.IValue|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IValue:interface'
        name: google.privacy.dlp.v2.IValue
        fullName: google.privacy.dlp.v2.IValue
      - name: '|null)'
        fullName: '|null)'
