### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
    summary: Represents an OutputStorageConfig.
    name: google.privacy.dlp.v2.OutputStorageConfig
    fullName: google.privacy.dlp.v2.OutputStorageConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IOutputStorageConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#outputSchema:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#table:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#type:member'
      - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:constructor(1)'
    summary: Constructs a new OutputStorageConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IOutputStorageConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IOutputStorageConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.create:member(1)'
    summary: Creates a new OutputStorageConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static create(properties?: google.privacy.dlp.v2.IOutputStorageConfig):
        google.privacy.dlp.v2.OutputStorageConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
        description: OutputStorageConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IOutputStorageConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decode:member(1)'
    summary: Decodes an OutputStorageConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.OutputStorageConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
        description: OutputStorageConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decodeDelimited:member(1)'
    summary: 'Decodes an OutputStorageConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.OutputStorageConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
        description: OutputStorageConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encode:member(1)'
    summary: Encodes the specified OutputStorageConfig message. Does not implicitly  messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encode(message: google.privacy.dlp.v2.IOutputStorageConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: OutputStorageConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IOutputStorageConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encodeDelimited:member(1)'
    summary: 'Encodes the specified OutputStorageConfig message, length delimited. Does not implicitly  messages.'
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IOutputStorageConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: OutputStorageConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IOutputStorageConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.fromObject:member(1)'
    summary: >-
      Creates an OutputStorageConfig message from a plain object. Also converts values to their respective internal
      types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.OutputStorageConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
        description: OutputStorageConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#outputSchema:member'
    summary: OutputStorageConfig outputSchema.
    name: outputSchema
    fullName: outputSchema
    langs:
      - typeScript
    type: property
    syntax:
      content: >-
        public outputSchema: (google.privacy.dlp.v2.OutputStorageConfig.OutputSchema|keyof typeof
        google.privacy.dlp.v2.OutputStorageConfig.OutputSchema);
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#outputSchema~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#table:member'
    summary: OutputStorageConfig table.
    name: table
    fullName: table
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public table?: (google.privacy.dlp.v2.IBigQueryTable|null);'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#table~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#toJSON:member(1)'
    summary: Converts this OutputStorageConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.toObject:member(1)'
    summary: Creates a plain object from an OutputStorageConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.OutputStorageConfig, options?:
        $protobuf.IConversionOptions): { [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: OutputStorageConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#type:member'
    summary: OutputStorageConfig type.
    name: type
    fullName: type
    langs:
      - typeScript
    type: property
    syntax:
      content: 'public type?: "table";'
      return:
        type:
          - '"table"'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.verify:member(1)'
    summary: Verifies an OutputStorageConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IOutputStorageConfig:interface'
    name: IOutputStorageConfig
    fullName: google.privacy.dlp.v2.IOutputStorageConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig:class'
    name: OutputStorageConfig
    fullName: google.privacy.dlp.v2.OutputStorageConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#outputSchema~0:complex'
    name: >-
      (google.privacy.dlp.v2.OutputStorageConfig.OutputSchema|keyof typeof
      google.privacy.dlp.v2.OutputStorageConfig.OutputSchema)
    fullName: >-
      (google.privacy.dlp.v2.OutputStorageConfig.OutputSchema|keyof typeof
      google.privacy.dlp.v2.OutputStorageConfig.OutputSchema)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.OutputSchema:enum'
        name: google.privacy.dlp.v2.OutputStorageConfig.OutputSchema
        fullName: google.privacy.dlp.v2.OutputStorageConfig.OutputSchema
      - name: '|keyof typeof '
        fullName: '|keyof typeof '
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.OutputSchema:enum'
        name: google.privacy.dlp.v2.OutputStorageConfig.OutputSchema
        fullName: google.privacy.dlp.v2.OutputStorageConfig.OutputSchema
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig#table~0:complex'
    name: (google.privacy.dlp.v2.IBigQueryTable|null)
    fullName: (google.privacy.dlp.v2.IBigQueryTable|null)
    spec.typeScript:
      - name: (
        fullName: (
      - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IBigQueryTable:interface'
        name: google.privacy.dlp.v2.IBigQueryTable
        fullName: google.privacy.dlp.v2.IBigQueryTable
      - name: '|null)'
        fullName: '|null)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.OutputStorageConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
