### YamlMime:UniversalReference
items:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
    summary: Represents a RedactConfig.
    name: google.privacy.dlp.v2.RedactConfig
    fullName: google.privacy.dlp.v2.RedactConfig
    langs:
      - typeScript
    type: class
    implements:
      - '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
    package: '@google-cloud/dlp!'
    children:
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:constructor(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.create:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encode:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encodeDelimited:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.fromObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig#toJSON:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.toObject:member(1)'
      - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.verify:member(1)'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:constructor(1)'
    summary: Constructs a new RedactConfig.
    name: (constructor)(properties)
    fullName: (constructor)(properties)
    langs:
      - typeScript
    type: constructor
    syntax:
      content: 'constructor(properties?: google.privacy.dlp.v2.IRedactConfig);'
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.create:member(1)'
    summary: Creates a new RedactConfig instance using the specified properties.
    name: create(properties)
    fullName: create(properties)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static create(properties?: google.privacy.dlp.v2.IRedactConfig): google.privacy.dlp.v2.RedactConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
        description: RedactConfig instance
      parameters:
        - id: properties
          description: Properties to set
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decode:member(1)'
    summary: Decodes a RedactConfig message from the specified reader or buffer.
    name: 'decode(reader, length)'
    fullName: 'decode(reader, length)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static decode(reader: ($protobuf.Reader|Uint8Array), length?: number):
        google.privacy.dlp.v2.RedactConfig;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
        description: RedactConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decode~0:complex'
        - id: length
          description: Message length if known beforehand
          type:
            - number
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decodeDelimited:member(1)'
    summary: 'Decodes a RedactConfig message from the specified reader or buffer, length delimited.'
    name: decodeDelimited(reader)
    fullName: decodeDelimited(reader)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static decodeDelimited(reader: ($protobuf.Reader|Uint8Array)): google.privacy.dlp.v2.RedactConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
        description: RedactConfig
      parameters:
        - id: reader
          description: Reader or buffer to decode from
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decodeDelimited~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encode:member(1)'
    summary: >-
      Encodes the specified RedactConfig message. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.verify:member(1)) messages.
    name: 'encode(message, writer)'
    fullName: 'encode(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static encode(message: google.privacy.dlp.v2.IRedactConfig, writer?: $protobuf.Writer): $protobuf.Writer;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encode~0:complex'
        description: Writer
      parameters:
        - id: message
          description: RedactConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encode~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encodeDelimited:member(1)'
    summary: >-
      Encodes the specified RedactConfig message, length delimited. Does not implicitly
      [verify](xref:@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.verify:member(1)) messages.
    name: 'encodeDelimited(message, writer)'
    fullName: 'encodeDelimited(message, writer)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static encodeDelimited(message: google.privacy.dlp.v2.IRedactConfig, writer?: $protobuf.Writer):
        $protobuf.Writer;
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encodeDelimited~0:complex'
        description: Writer
      parameters:
        - id: message
          description: RedactConfig message or plain object to encode
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
        - id: writer
          description: Writer to encode to
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encodeDelimited~1:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.fromObject:member(1)'
    summary: Creates a RedactConfig message from a plain object. Also converts values to their respective internal types.
    name: fromObject(object)
    fullName: fromObject(object)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static fromObject(object: { [k: string]: any }): google.privacy.dlp.v2.RedactConfig;'
      return:
        type:
          - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
        description: RedactConfig
      parameters:
        - id: object
          description: Plain object
          type:
            - '{ [k: string]: any }'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig#toJSON:member(1)'
    summary: Converts this RedactConfig to JSON.
    name: toJSON()
    fullName: toJSON()
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public toJSON(): { [k: string]: any };'
      return:
        type:
          - '{ [k: string]: any }'
        description: JSON object
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.toObject:member(1)'
    summary: Creates a plain object from a RedactConfig message. Also converts values to other types if specified.
    name: 'toObject(message, options)'
    fullName: 'toObject(message, options)'
    langs:
      - typeScript
    type: method
    syntax:
      content: >-
        public static toObject(message: google.privacy.dlp.v2.RedactConfig, options?: $protobuf.IConversionOptions): {
        [k: string]: any };
      return:
        type:
          - '{ [k: string]: any }'
        description: Plain object
      parameters:
        - id: message
          description: RedactConfig
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
        - id: options
          description: Conversion options
          type:
            - '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.toObject~0:complex'
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.verify:member(1)'
    summary: Verifies a RedactConfig message.
    name: verify(message)
    fullName: verify(message)
    langs:
      - typeScript
    type: method
    syntax:
      content: 'public static verify(message: { [k: string]: any }): (string|null);'
      return:
        type:
          - (string|null)
        description: '`null` if valid, otherwise the reason why it is not'
      parameters:
        - id: message
          description: Plain object to verify
          type:
            - '{ [k: string]: any }'
references:
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.IRedactConfig:interface'
    name: IRedactConfig
    fullName: google.privacy.dlp.v2.IRedactConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig:class'
    name: RedactConfig
    fullName: google.privacy.dlp.v2.RedactConfig
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decode~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.decodeDelimited~0:complex'
    name: ($protobuf.Reader|Uint8Array)
    fullName: ($protobuf.Reader|Uint8Array)
    spec.typeScript:
      - name: ($protobuf.
        fullName: ($protobuf.
      - uid: 'protobufjs!Reader:class'
        name: Reader
        fullName: Reader
      - name: '|'
        fullName: '|'
      - uid: '!Uint8Array:interface'
        name: Uint8Array
        fullName: Uint8Array
      - name: )
        fullName: )
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encode~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encode~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encodeDelimited~0:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.encodeDelimited~1:complex'
    name: $protobuf.Writer
    fullName: $protobuf.Writer
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!Writer:class'
        name: Writer
        fullName: Writer
  - uid: '@google-cloud/dlp!google.privacy.dlp.v2.RedactConfig.toObject~0:complex'
    name: $protobuf.IConversionOptions
    fullName: $protobuf.IConversionOptions
    spec.typeScript:
      - name: $protobuf.
        fullName: $protobuf.
      - uid: 'protobufjs!IConversionOptions:interface'
        name: IConversionOptions
        fullName: IConversionOptions
